name = "ovalsaone"
compatibility_date = "2024-01-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "_site"

# Variables d'environnement pour les Functions
[vars]
SMTP_FROM = "onboarding@resend.dev"  # Changer pour votre domaine vérifié dans Resend
CONTACT_EMAIL = "kevin.menant@gmail.com" # "contact@ovalsaone.fr"

# Secrets (configurer via Cloudflare Dashboard ou `wrangler pages secret put`):
# - RESEND_API_KEY: Votre clé API Resend
